
/*
Auto-generated by CVXPYgen on September 18, 2025 at 16:19:06.
Content: Variable definitions.
*/

#include "cpg_workspace.h"

// Vector containing flattened user-defined parameters
cpg_float cpg_params_vec[7] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)2.24089319920145779719,
(cpg_float)1.86755799014996748397,
(cpg_float)-0.97727787987641101530,
(cpg_float)1.00000000000000000000,
};

// Sparse mappings from user-defined to canonical parameters
cpg_int canon_A_map_i[8] = {
6,
6,
6,
0,
6,
1,
2,
6,
};
cpg_int canon_A_map_p[9] = {
0,
1,
2,
3,
4,
5,
6,
7,
8,
};
cpg_float canon_A_map_x[8] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
};
cpg_csc canon_A_map = {canon_A_map_p, canon_A_map_i, canon_A_map_x, 8};

cpg_int canon_b_map_i[3] = {
3,
4,
5,
};
cpg_int canon_b_map_p[6] = {
0,
1,
2,
3,
3,
3,
};
cpg_float canon_b_map_x[3] = {
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
};
cpg_csc canon_b_map = {canon_b_map_p, canon_b_map_i, canon_b_map_x, 3};

// Canonical parameters
cpg_int canon_P_i[3] = {
0,
1,
2,
};
cpg_int canon_P_p[6] = {
0,
1,
2,
3,
3,
3,
};
cpg_float canon_P_x[3] = {
(cpg_float)2.00000000000000000000,
(cpg_float)2.00000000000000000000,
(cpg_float)2.00000000000000000000,
};
cpg_csc canon_P = {canon_P_p, canon_P_i, canon_P_x, 3};

cpg_float canon_c[5] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_int canon_A_i[8] = {
0,
1,
2,
0,
3,
0,
1,
4,
};
cpg_int canon_A_p[6] = {
0,
1,
2,
3,
5,
8,
};
cpg_float canon_A_x[8] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)-1.00000000000000000000,
};
cpg_csc canon_A = {canon_A_p, canon_A_i, canon_A_x, 8};

cpg_float canon_b[5] = {
(cpg_float)2.24089319920145779719,
(cpg_float)1.86755799014996748397,
(cpg_float)-0.97727787987641101530,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

// Struct containing canonical parameters
Canon_Params_t Canon_Params = {
.P = &canon_P,
.c = (cpg_float *) &canon_c,
.d = 0.00000000000000000000,
.A = &canon_A,
.b = (cpg_float *) &canon_b,
};

// Struct containing flags for outdated canonical parameters
Canon_Outdated_t Canon_Outdated = {
.P = 1,
.c = 1,
.d = 1,
.A = 1,
.b = 1,
};

// User-defined variables
// Struct containing primal solution
CPG_Prim_t CPG_Prim = {
.x = (cpg_float *) &scs_x + 3,
};
// Struct containing dual solution
CPG_Dual_t CPG_Dual = {
.d0 = (cpg_float *) &scs_y + 3,
};

// Struct containing solver info
CPG_Info_t CPG_Info = {
.obj_val = 0,
.iter = 0,
.status = "unknown",
.pri_res = 0,
.dua_res = 0,
};

// Struct containing solution and info
CPG_Result_t CPG_Result = {
.prim = &CPG_Prim,
.dual = &CPG_Dual,
.info = &CPG_Info,
};

// SCS matrix P
ScsMatrix Scs_P = {
.x = (cpg_float *) &canon_P_x,
.i = (cpg_int *) &canon_P_i,
.p = (cpg_int *) &canon_P_p,
.m = 5,
.n = 5,
};

// SCS matrix A
ScsMatrix Scs_A = {
.x = (cpg_float *) &canon_A_x,
.i = (cpg_int *) &canon_A_i,
.p = (cpg_int *) &canon_A_p,
.m = 5,
.n = 5,
};

// Struct containing SCS data
ScsData Scs_D = {
.m = 5,
.n = 5,
.A = &Scs_A,
.P = &Scs_P,
.b = (cpg_float *) &canon_b,
.c = (cpg_float *) &canon_c,
};

// Struct containing SCS cone data
ScsCone Scs_K = {
.z = 3,
.l = 2,
.bu = SCS_NULL,
.bl = SCS_NULL,
.bsize = 0,
.q = SCS_NULL,
.qsize = 0,
.s = SCS_NULL,
.ssize = 0,
.ep = 0,
.ed = 0,
.p = SCS_NULL,
.psize = 0,
};

// Struct containing SCS settings
ScsSettings Canon_Settings = {
.normalize = 1,
.scale = 0.1,
.adaptive_scale = 1,
.rho_x = 1e-6,
.max_iters = 1e5,
.eps_abs = 1e-4,
.eps_rel = 1e-4,
.eps_infeas = 1e-7,
.alpha = 1.5,
.time_limit_secs = 0,
.verbose = 0,
.warm_start = 0,
.acceleration_lookback = 0,
.acceleration_interval = 1,
.write_data_filename = SCS_NULL,
.log_csv_filename = SCS_NULL,
};

// SCS solution
cpg_float scs_x[5] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};
cpg_float scs_y[5] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};
cpg_float scs_s[5] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

// Struct containing SCS solution
ScsSolution Scs_Sol = {
.x = (cpg_float *) &scs_x,
.y = (cpg_float *) &scs_y,
.s = (cpg_float *) &scs_s,
};

// Struct containing SCS information
ScsInfo Scs_Info = {
.iter = 0,
.status = "unknown",
.status_val = 0,
.scale_updates = 0,
.pobj = 0,
.dobj = 0,
.res_pri = 99,
.res_dual = 99,
.gap = 99,
.res_infeas = 99,
.res_unbdd_a = 99,
.res_unbdd_p = 99,
.comp_slack = 99,
.setup_time = 0,
.solve_time = 0,
.scale = 1,
.rejected_accel_steps = 0,
.accepted_accel_steps = 0,
.lin_sys_time = 0,
.cone_time = 0,
.accel_time = 0,
};

// Pointer to struct containing SCS workspace
ScsWork* Scs_Work = 0;
