
/*
Auto-generated by CVXPYgen on September 18, 2025 at 16:02:00.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_lamb_sm(cpg_float val){
  cpg_params_vec[0] = val;
  Canon_Outdated.P = 1;
}

void cpg_update_kappa(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1] = val;
  Canon_Outdated.c = 1;
}

void cpg_update_A(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+9] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_w(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+33] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_u_min(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+36] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_u_max(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+44] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_u_prev(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+52] = val;
  Canon_Outdated.b = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_P(){
  for(i=0; i<11; i++){
    Canon_Params.P->x[i] = 0;
    for(j=canon_P_map.p[i]; j<canon_P_map.p[i+1]; j++){
      Canon_Params.P->x[i] += canon_P_map.x[j]*cpg_params_vec[canon_P_map.i[j]];
    }
  }
}

void cpg_canonicalize_c(){
  for(i=0; i<27; i++){
    Canon_Params.c[i] = 0;
    for(j=canon_c_map.p[i]; j<canon_c_map.p[i+1]; j++){
      Canon_Params.c[i] += canon_c_map.x[j]*cpg_params_vec[canon_c_map.i[j]];
    }
  }
}

void cpg_canonicalize_A(){
  for(i=0; i<91; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_b(){
  for(i=0; i<43; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (Scs_Info.pobj);
  CPG_Info.iter = Scs_Info.iter;
  CPG_Info.status = Scs_Info.status;
  CPG_Info.pri_res = Scs_Info.res_pri;
  CPG_Info.dua_res = Scs_Info.res_dual;
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.P) {
    cpg_canonicalize_P();
  }
  if (Canon_Outdated.c) {
    cpg_canonicalize_c();
  }
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (!Scs_Work ) {
    Scs_Work = scs_init(&Scs_D, &Scs_K, &Canon_Settings);
  } else {
    if (Canon_Outdated.P || Canon_Outdated.A) {
      Scs_Work = scs_init(&Scs_D, &Scs_K, &Canon_Settings);
    } else {
      if (Canon_Outdated.b && Canon_Outdated.c) {
        scs_update(Scs_Work, Canon_Params.b, Canon_Params.c);
      } else {
        if (Canon_Outdated.b) {
          scs_update(Scs_Work, Canon_Params.b, SCS_NULL);
        }
        if (Canon_Outdated.c) {
          scs_update(Scs_Work, SCS_NULL, Canon_Params.c);
        }
      }
    }
  }
  // Solve with SCS
  scs_solve(Scs_Work, &Scs_Sol, &Scs_Info, (Scs_Work && Canon_Settings.warm_start));
  // Retrieve results
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.P = 0;
  Canon_Outdated.c = 0;
  Canon_Outdated.A = 0;
  Canon_Outdated.b = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  scs_set_default_settings(&Canon_Settings);
}

void cpg_set_solver_normalize(cpg_int normalize_new){
  Canon_Settings.normalize = normalize_new;
}

void cpg_set_solver_scale(cpg_float scale_new){
  Canon_Settings.scale = scale_new;
}

void cpg_set_solver_adaptive_scale(cpg_int adaptive_scale_new){
  Canon_Settings.adaptive_scale = adaptive_scale_new;
}

void cpg_set_solver_rho_x(cpg_float rho_x_new){
  Canon_Settings.rho_x = rho_x_new;
}

void cpg_set_solver_max_iters(cpg_int max_iters_new){
  Canon_Settings.max_iters = max_iters_new;
}

void cpg_set_solver_eps_abs(cpg_float eps_abs_new){
  Canon_Settings.eps_abs = eps_abs_new;
}

void cpg_set_solver_eps_rel(cpg_float eps_rel_new){
  Canon_Settings.eps_rel = eps_rel_new;
}

void cpg_set_solver_eps_infeas(cpg_float eps_infeas_new){
  Canon_Settings.eps_infeas = eps_infeas_new;
}

void cpg_set_solver_alpha(cpg_float alpha_new){
  Canon_Settings.alpha = alpha_new;
}

void cpg_set_solver_time_limit_secs(cpg_float time_limit_secs_new){
  Canon_Settings.time_limit_secs = time_limit_secs_new;
}

void cpg_set_solver_verbose(cpg_int verbose_new){
  Canon_Settings.verbose = verbose_new;
}

void cpg_set_solver_warm_start(cpg_int warm_start_new){
  Canon_Settings.warm_start = warm_start_new;
}

void cpg_set_solver_acceleration_lookback(cpg_int acceleration_lookback_new){
  Canon_Settings.acceleration_lookback = acceleration_lookback_new;
}

void cpg_set_solver_acceleration_interval(cpg_int acceleration_interval_new){
  Canon_Settings.acceleration_interval = acceleration_interval_new;
}

void cpg_set_solver_write_data_filename(const char* write_data_filename_new){
  Canon_Settings.write_data_filename = write_data_filename_new;
}

void cpg_set_solver_log_csv_filename(const char* log_csv_filename_new){
  Canon_Settings.log_csv_filename = log_csv_filename_new;
}
