
/*
Auto-generated by CVXPYgen on September 18, 2025 at 16:02:00.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_lamb_sm(0.50000000000000000000);
  cpg_update_kappa(0, 0.10000000000000000555);
  cpg_update_A(0, 1.00000000000000000000);
  cpg_update_w(0, 1.00000000000000000000);
  cpg_update_u_min(0, -1.00000000000000000000);
  cpg_update_u_max(0, 1.00000000000000000000);
  cpg_update_u_prev(0, 0.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<8; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<8; i++) {
    printf("delta_u[%d] = %f\n", i, CPG_Result.prim->delta_u[i]);
  }

  // Print dual solution
  for(i=0; i<8; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<8; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<8; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }

  return 0;

}
