
/*
Auto-generated by CVXPYgen on September 18, 2025 at 16:02:00.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    double lamb_sm;
    std::array<double, 8> kappa;
    std::array<double, 24> A;
    std::array<double, 3> w;
    std::array<double, 8> u_min;
    std::array<double, 8> u_max;
    std::array<double, 8> u_prev;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool lamb_sm;
    bool kappa;
    bool A;
    bool w;
    bool u_min;
    bool u_max;
    bool u_prev;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 8> u;
    std::array<double, 8> delta_u;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 8> d0;
    std::array<double, 8> d1;
    std::array<double, 8> d2;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    char* status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
