
/*
Auto-generated by CVXPYgen on September 18, 2025 at 15:51:45.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    std::array<double, 1440> p;
    std::array<double, 1440> s;
    double gamma;
    double D;
    double C;
    double Q;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool p;
    bool s;
    bool gamma;
    bool D;
    bool C;
    bool Q;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 1440> u;
    std::array<double, 1441> q;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 1440> d0;
    std::array<double, 1440> d1;
    std::array<double, 1440> d2;
    std::array<double, 1441> d3;
    std::array<double, 1441> d4;
    double d5;
    double d6;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    int status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
