
/*
Auto-generated by CVXPYgen on September 18, 2025 at 15:51:45.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_p(0, 3.00000000000000000000);
  cpg_update_s(0, 0.30000000000000004441);
  cpg_update_gamma(100.00000000000000000000);
  cpg_update_D(0.00416666666666666661);
  cpg_update_C(0.00208333333333333330);
  cpg_update_Q(1.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<1440; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<1441; i++) {
    printf("q[%d] = %f\n", i, CPG_Result.prim->q[i]);
  }

  // Print dual solution
  for(i=0; i<1440; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<1440; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<1440; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<1441; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<1441; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  printf("d5 = %f\n", CPG_Result.dual->d5);
  printf("d6 = %f\n", CPG_Result.dual->d6);

  return 0;

}
