
/*
Auto-generated by CVXPYgen on September 18, 2025 at 15:51:45.
Content: Function declarations.
*/

#include "cpg_workspace.h"

// Update user-defined parameter values
extern void cpg_update_p(cpg_int idx, cpg_float val);
extern void cpg_update_s(cpg_int idx, cpg_float val);
extern void cpg_update_gamma(cpg_float val);
extern void cpg_update_D(cpg_float val);
extern void cpg_update_C(cpg_float val);
extern void cpg_update_Q(cpg_float val);

// Map user-defined to canonical parameters
extern void cpg_canonicalize_c();
extern void cpg_canonicalize_b();
extern void cpg_canonicalize_h();

// Retrieve primal solution in terms of user-defined variables
extern void cpg_retrieve_prim();

// Retrieve dual solution in terms of user-defined constraints
extern void cpg_retrieve_dual();

// Retrieve solver information
extern void cpg_retrieve_info();

// Copy canonical parameters for preconditioning
extern void cpg_copy_c();
extern void cpg_copy_A();
extern void cpg_copy_b();
extern void cpg_copy_G();
extern void cpg_copy_h();
extern void cpg_copy_all();

// Solve via canonicalization, canonical solve, retrieval
extern void cpg_solve();

// Update solver settings
extern void cpg_set_solver_default_settings();
extern void cpg_set_solver_feastol(cpg_float feastol_new);
extern void cpg_set_solver_abstol(cpg_float abstol_new);
extern void cpg_set_solver_reltol(cpg_float reltol_new);
extern void cpg_set_solver_feastol_inacc(cpg_float feastol_inacc_new);
extern void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new);
extern void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new);
extern void cpg_set_solver_maxit(cpg_int maxit_new);
