
/*
Auto-generated by CVXPYgen on September 18, 2025 at 16:02:00.
Content: Python binding with pybind11.
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include <chrono>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

static int i;

CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.lamb_sm) {
        cpg_update_lamb_sm(CPG_Params_cpp.lamb_sm);
    }
    if (CPG_Updated_cpp.kappa) {
        for(i=0; i<8; i++) {
            cpg_update_kappa(i, CPG_Params_cpp.kappa[i]);
        }
    }
    if (CPG_Updated_cpp.A) {
        for(i=0; i<24; i++) {
            cpg_update_A(i, CPG_Params_cpp.A[i]);
        }
    }
    if (CPG_Updated_cpp.w) {
        for(i=0; i<3; i++) {
            cpg_update_w(i, CPG_Params_cpp.w[i]);
        }
    }
    if (CPG_Updated_cpp.u_min) {
        for(i=0; i<8; i++) {
            cpg_update_u_min(i, CPG_Params_cpp.u_min[i]);
        }
    }
    if (CPG_Updated_cpp.u_max) {
        for(i=0; i<8; i++) {
            cpg_update_u_max(i, CPG_Params_cpp.u_max[i]);
        }
    }
    if (CPG_Updated_cpp.u_prev) {
        for(i=0; i<8; i++) {
            cpg_update_u_prev(i, CPG_Params_cpp.u_prev[i]);
        }
    }

    // Solve
    auto ASA_start = std::chrono::high_resolution_clock::now();
    cpg_solve();
    auto ASA_end = std::chrono::high_resolution_clock::now();

    // Arrange and return results
    CPG_Prim_cpp_t CPG_Prim_cpp {};
    for(i=0; i<8; i++) {
        CPG_Prim_cpp.u[i] = CPG_Prim.u[i];
    }
    for(i=0; i<8; i++) {
        CPG_Prim_cpp.delta_u[i] = CPG_Prim.delta_u[i];
    }
    CPG_Dual_cpp_t CPG_Dual_cpp {};
    for(i=0; i<8; i++) {
        CPG_Dual_cpp.d0[i] = CPG_Dual.d0[i];
    }
    for(i=0; i<8; i++) {
        CPG_Dual_cpp.d1[i] = CPG_Dual.d1[i];
    }
    for(i=0; i<8; i++) {
        CPG_Dual_cpp.d2[i] = CPG_Dual.d2[i];
    }
    CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = CPG_Info.obj_val;
    CPG_Info_cpp.iter = CPG_Info.iter;
    CPG_Info_cpp.status = CPG_Info.status;
    CPG_Info_cpp.pri_res = CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = CPG_Info.dua_res;
    std::chrono::duration<double> elapsed = ASA_end - ASA_start;
    CPG_Info_cpp.time = elapsed.count();
    CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<CPG_Params_cpp_t>(m, "cpg_params")
            .def(py::init<>())
            .def_readwrite("lamb_sm", &CPG_Params_cpp_t::lamb_sm)
            .def_readwrite("kappa", &CPG_Params_cpp_t::kappa)
            .def_readwrite("A", &CPG_Params_cpp_t::A)
            .def_readwrite("w", &CPG_Params_cpp_t::w)
            .def_readwrite("u_min", &CPG_Params_cpp_t::u_min)
            .def_readwrite("u_max", &CPG_Params_cpp_t::u_max)
            .def_readwrite("u_prev", &CPG_Params_cpp_t::u_prev)
            ;

    py::class_<CPG_Updated_cpp_t>(m, "cpg_updated")
            .def(py::init<>())
            .def_readwrite("lamb_sm", &CPG_Updated_cpp_t::lamb_sm)
            .def_readwrite("kappa", &CPG_Updated_cpp_t::kappa)
            .def_readwrite("A", &CPG_Updated_cpp_t::A)
            .def_readwrite("w", &CPG_Updated_cpp_t::w)
            .def_readwrite("u_min", &CPG_Updated_cpp_t::u_min)
            .def_readwrite("u_max", &CPG_Updated_cpp_t::u_max)
            .def_readwrite("u_prev", &CPG_Updated_cpp_t::u_prev)
            ;

    py::class_<CPG_Prim_cpp_t>(m, "cpg_prim")
            .def(py::init<>())
            .def_readwrite("u", &CPG_Prim_cpp_t::u)
            .def_readwrite("delta_u", &CPG_Prim_cpp_t::delta_u)
            ;

    py::class_<CPG_Dual_cpp_t>(m, "cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &CPG_Dual_cpp_t::d1)
            .def_readwrite("d2", &CPG_Dual_cpp_t::d2)
            ;

    py::class_<CPG_Info_cpp_t>(m, "cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &CPG_Info_cpp_t::iter)
            .def_readwrite("status", &CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &CPG_Info_cpp_t::time)
            ;

    py::class_<CPG_Result_cpp_t>(m, "cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &CPG_Result_cpp_t::info)
            ;

    m.def("solve", &solve_cpp);

    m.def("set_solver_default_settings", &cpg_set_solver_default_settings);
    m.def("set_solver_normalize", &cpg_set_solver_normalize);
    m.def("set_solver_scale", &cpg_set_solver_scale);
    m.def("set_solver_adaptive_scale", &cpg_set_solver_adaptive_scale);
    m.def("set_solver_rho_x", &cpg_set_solver_rho_x);
    m.def("set_solver_max_iters", &cpg_set_solver_max_iters);
    m.def("set_solver_eps_abs", &cpg_set_solver_eps_abs);
    m.def("set_solver_eps_rel", &cpg_set_solver_eps_rel);
    m.def("set_solver_eps_infeas", &cpg_set_solver_eps_infeas);
    m.def("set_solver_alpha", &cpg_set_solver_alpha);
    m.def("set_solver_time_limit_secs", &cpg_set_solver_time_limit_secs);
    m.def("set_solver_verbose", &cpg_set_solver_verbose);
    m.def("set_solver_warm_start", &cpg_set_solver_warm_start);
    m.def("set_solver_acceleration_lookback", &cpg_set_solver_acceleration_lookback);
    m.def("set_solver_acceleration_interval", &cpg_set_solver_acceleration_interval);
    m.def("set_solver_write_data_filename", &cpg_set_solver_write_data_filename);
    m.def("set_solver_log_csv_filename", &cpg_set_solver_log_csv_filename);

}
